import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gradient-to-b from-white to-slate-50 text-foreground antialiased">
        <Navbar />
        <main className="mx-auto w-full max-w-6xl px-6 py-8">{children}</main>
        <footer className="border-t border-border/40 bg-white/50 mt-12 py-6 text-center text-sm text-muted-foreground">
          © {new Date().getFullYear()} OsarPosar — All rights reserved.
        </footer>
      </body>
    </html>
  );
}
